"""hyprland-events — Typed event dispatch for Hyprland."""

from .dispatcher import EventDispatcher as EventDispatcher
from .types import (
    ActiveLayoutEvent as ActiveLayoutEvent,
    ActiveSpecialEvent as ActiveSpecialEvent,
    ActiveWindowEvent as ActiveWindowEvent,
    ActiveWindowV2Event as ActiveWindowV2Event,
    BellEvent as BellEvent,
    CloseLayerEvent as CloseLayerEvent,
    CloseWindowEvent as CloseWindowEvent,
    ConfigReloadedEvent as ConfigReloadedEvent,
    CreateWorkspaceEvent as CreateWorkspaceEvent,
    DestroyWorkspaceEvent as DestroyWorkspaceEvent,
    FloatingEvent as FloatingEvent,
    FocusedMonitorEvent as FocusedMonitorEvent,
    FullscreenEvent as FullscreenEvent,
    IgnoreGroupLockEvent as IgnoreGroupLockEvent,
    KillEvent as KillEvent,
    LockGroupsEvent as LockGroupsEvent,
    MinimizeEvent as MinimizeEvent,
    MonitorAddedEvent as MonitorAddedEvent,
    MonitorRemovedEvent as MonitorRemovedEvent,
    MoveIntoGroupEvent as MoveIntoGroupEvent,
    MoveOutOfGroupEvent as MoveOutOfGroupEvent,
    MoveWindowEvent as MoveWindowEvent,
    MoveWorkspaceEvent as MoveWorkspaceEvent,
    OpenLayerEvent as OpenLayerEvent,
    OpenWindowEvent as OpenWindowEvent,
    PinEvent as PinEvent,
    RenameWorkspaceEvent as RenameWorkspaceEvent,
    ScreencastEvent as ScreencastEvent,
    SubmapEvent as SubmapEvent,
    ToggleGroupEvent as ToggleGroupEvent,
    UrgentEvent as UrgentEvent,
    WindowTitleEvent as WindowTitleEvent,
    WorkspaceEvent as WorkspaceEvent,
    parse_event as parse_event,
)
